### ISSUE TITLE
dirty migrations

### ISSUE THREAD

**Issue by gedw99** [mergestat/mergestat#372]
Could Atlas help with automatic creation of the Migrations ?

https://github.com/ariga/atlas

**Comment by samrose** [comment]
What is the process to intervene and force migrations?

**Comment by patrickdevivo** [comment]
> What is the process to intervene and force migrations? 

Right now it's not great - it requires manual intervention in the database, which is not sustainable with our current deployment/distribution model. One of the main reasons we're looking for either an alternative tool or a process we can apply to avoid a manual intervention

**Comment by gedw99** [comment]
One pattern that I have used is to make the migrations an event . 

So when you change the sql schema , it’s an event and so subscribers will do it a Ross time and space if an async message broker like NATS is used. 

The idea is to gen the events into nats so that consumers pick it up eventually . Web hooks are useless because if the subscriber is not live it’s lost to the ether. 

Hope this makes sense. 

Nats holds the event and wil give the event to the subscribers when they one day boot up or are currently running

**Comment by amenowanna** [comment]
Manual intervention is still needed depending on the migration issue but we have added automation to reset the `dirty` state back to reduce one of the items that has to be done to fix the migrations. Most migration issues we have had historically were caused by not making idempotent migrations and we really don't see as many issues anymore.
