### ISSUE TITLE
Need help how can I fix gitsync timeout issue

### ISSUE THREAD

**Issue by kapilkumawat86** [mergestat/mergestat#705]
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/57665511/211189096-6525e1f5-b9f3-44f4-b279-a226119ab689.png">
It's happening because of the large repo, Can I say I just need last year's data or filter based on user?

**Comment by patrickdevivo** [comment]
Hi @kapilkumawat86 - at the moment there's not a way to filter data at collection/sync time (though that is something we should add support for via user-defined configuration of our syncs).

Something you could do to address this particular issue, is set the `GITHUB_PER_PAGE` in the `worker` service. If you're using `docker-compose` you can add a line [here](https://github.com/mergestat/mergestat/blob/main/docker-compose.yaml#L33).

The default value is [50](https://github.com/mergestat/mergestat-lite/blob/97fed801a60253cf4df29cffb198af0499784e67/extensions/internal/github/utils.go#L76), but sometimes that causes issues with the GitHub API (a page of data may be too big and trip a timeout/error). I would suggest lowering it to 30 or even 10. This will make the sync running time longer, but may avoid some of these timeouts.

We are working on:

- Configuration options per sync type (so that you can manage these parameters fora sync run in the UI)
- Implementing API retries in our GitHub API syncs

**Comment by kapilkumawat86** [comment]
Thanks let me try this and get back to you

**Comment by amenowanna** [comment]
@kapilkumawat86 the suggested change here is what we recommend to resolve this issue and continue to have success with it. If you are still having issues let us know.
