### ISSUE TITLE
Implement the UI for direct SQL queries

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#88]
Implement the UI for #87.

We should have sufficient designs in place from the `app.mergestat.com` implementation.

**Comment by emilyvandewalle** [comment]
The Figma designs so far for this can be found [here](https://www.figma.com/file/a6uVmHun0vKY08mGAsvHjJ/MergeStat---Self-Hosted-App?node-id=3102%3A58384). It's still work in progress and I didn't get to some details yet for the future version (like the auto complete, database references, query charts, etc...), but wanted to check in between for feedback:

# First simple version

## Initial state
![image](https://user-images.githubusercontent.com/36261498/192336295-8f72443a-61a5-4c2f-939c-60d7af874a00.png)
- Experimented with moving the main actions (`Execute`) in the top header/toolbar (instead of part of the query editor)

## Loading state
![image](https://user-images.githubusercontent.com/36261498/192336602-f18ba858-ee09-4285-b5a7-ee6d0fd61199.png)
- Using a skeleton loading could decrease the perceived loading time and give the user a better expectation of the loaded state
- Mostly used for initial full-page loading states, but I think it could work here too
- **Reference:** I thought this was a good in-depth reference in general for loading feedback: [https://pencilandpaper.io/articles/ux-pattern-analysis-loading-feedback/#tldr-core-principles](https://pencilandpaper.io/articles/ux-pattern-analysis-loading-feedback/#tldr-core-principles ). This article recommends different loading approaches based on the loading time (`indeterminate` vs `determinate` for longer than 10s). Do we know an average loading time or does it vary a lot depending on the query/other factors?

## Success state
![image](https://user-images.githubusercontent.com/36261498/192336649-22623504-047d-4270-ae7a-d1cb78cc2427.png)
- Experimented with making the results table full width to make better use of the space available

### More results than row limit
![image](https://user-images.githubusercontent.com/36261498/192336779-0e632648-4bac-496c-b9f8-e565b53b19df.png)

### Fullscreen results view
![image](https://user-images.githubusercontent.com/36261498/192336894-9a81565e-0820-4671-a7e1-6b779584fbd9.png)
- Maybe we could make the `Query results` view expandable/full screen (a bit like in popsql) as I can imagine once you've ran the query sometimes you want to zoom in on the results. 
- We could also keep the resizing of the `Query editor` vs. `Query results` area which also helps with that

## Error state
![image](https://user-images.githubusercontent.com/36261498/192337166-33e1bc2d-0241-4c81-84bc-1e664f73d0b4.png)

# First explorations for future version
As part of exploring the future version I experimented with a couple of possible navigation patterns within `Queries`. 
I'm leaning towards the master detail view as both the `Saved queries`, `History` and `Example queries` would lead to a similar editor view, but I'm curious to know your perspective on this

## Navigation

### Master detail view
![image](https://user-images.githubusercontent.com/36261498/192337665-554bae94-6888-44f6-8eeb-a58f6eccc8b8.png)

![image](https://user-images.githubusercontent.com/36261498/192337693-13d1aa4a-b019-458a-b1f7-6d0c68e6387c.png)

- A master detail view where you can select a query on the left side which opens a new query tab (like in code editors for example)
- A master detail view makes it easier to reference/open multiple queries
- The downside is that this takes up valuable screen space, but we could make the master detail view collapsible to counter this

### Sub module navigation
![image](https://user-images.githubusercontent.com/36261498/192338008-fc952fc2-af71-4d17-9025-edcdd7312ee8.png)

![image](https://user-images.githubusercontent.com/36261498/192338031-0faf5ebf-bf7a-4ae0-a2ed-a3ee1e74f542.png)

- The idea here is that `Editor`, `Saved queries`, `History`, `Example queries`, ... are sub views of `Queries`. Opening a saved query leads to a new tab on the `Editor` view 

### Queries overview > Query detail
![image](https://user-images.githubusercontent.com/36261498/192338272-230b9e49-706d-4741-8a31-ea2c0ccf4254.png)

![image](https://user-images.githubusercontent.com/36261498/192338309-3a096973-1d6c-4919-ba54-afb6fbb6a5d2.png)
- I also wanted to try a more traditional navigation with an overview of the queries which lead to a detailed view for each query
- I think this could make navigating to the query editor a bit slower at first sight


I'll keep exploring a bit in general, but would be great to have your first general feedback as well as your feedback on the different navigation patterns. 

(I'm both open to async feedback and discussing this in a call together!)
