### ISSUE TITLE
Container-based sync logs are appearing "out of order"

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/mergestat#970]
Logs appearing out of order because insertion time is the same for all in a batch. Could we use a logged_at or counter/index in the timestamp?

**Comment by riyaz-ali** [comment]
@amenowanna I remember we discussed about postgres' ordering of `uuid` columns and seeing if doing `ORDER BY logged_at, id` would use the entry's insertion order and solve this issue. 

But I found these two - [(1)](https://stackoverflow.com/a/47921503/6611700) [(2)](https://stackoverflow.com/q/43238882/6611700) - stackoverflow which suggests that might not be the case, and the `UUID` comparison is actually based on lexical compare (?) of the byte string only.

So, instead of looking further into that, I addressed this by adding a 16-bit `position` field in the `sqlq.job_logs` table that is managed using a _cycling_ sequence (since we do not need _uniqueness_). Refer to the linked PR for implementation details 🙌
